### PR TITLE
Fix initial 2i AAE test backend entries

### PR DESCRIPTION
**Pull request by engelsanchez**

### CODE REVIEW

**Comment by seancribbs** [comment]
This is broken. It doesn't link the new test records to any projects, and so they don't show up in the scorecard.

**Comment by engelsanchez** [comment]
@seancribbs I tested now locally with the dump of the database you gave me and it looks like it works.  Also added the 'N' entry for multi, including Artie's help text.

**Comment by seancribbs** [comment]
:+1: would seed again

**Comment by seancribbs** [comment]
Merging and deploying

**Pull request merged**
