### PR TITLE
Add server sent events.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
@seancribbs 

Obsoletes #31.

### CODE REVIEW

**Comment by seancribbs** [comment]
Let's redo this now that #38 is completed and ready for review.

**Comment by cmeiklejohn** [comment]
Rebased against master.

**Comment by seancribbs** [comment]
It might be nice to have some indication in the UI that a new item was received, like an alert or something?

**Comment by seancribbs** [comment]
We should also get on Revision 11 of data, given the changes from this week. https://github.com/emberjs/data/blob/master/BREAKING_CHANGES.md

**Comment by cmeiklejohn** [comment]
When you say alert, I really want to put an `alert();` in. :fish:

**Comment by cmeiklejohn** [comment]
I'm going to do the revision 11 upgrade later as it requires an ember bump which breaks a large amount of the application.

**Comment by cmeiklejohn** [comment]
@joedevivo 

You have to click a link to be prompted, but then you'll have webkit notifications for any new results being posted to GiddyUp.

If you ask me, not bad, for a human.

**Comment by cmeiklejohn** [comment]
Screen Shot 2013-01-04 at 5 36 19 PM

**Comment by joedevivo** [comment]
That's hot.

**Comment by joedevivo** [comment]
looks and works great. Can we add more information to the alert?

something like 

GiddyUp: New ${Pass|Fail} on ${ScorecardShortName}
hostname
$Testname | $Backend | $Platform
$HudsonQuote

**Comment by cmeiklejohn** [comment]
"On it." - Hudson

**Comment by joedevivo** [comment]
+1 for phat new alerts

**Pull request merged**
