### PR TITLE
Clean up, and ensure we always load record into RA.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
This fixes a problem with SSE where a record doesn't show up if the association record-array already exists with a fixed set of identifiers.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@seancribbs I think this addresses the results not showing up.  I also can not reproduce the 'live' error locally at all, but it shouldn't be a problem because it will reconnect every 2 seconds per the spec.

**Comment by cmeiklejohn** [comment]
Tagging @joedevivo for review if he has time.  Way to test: local up the scorecard, run a test and the bubble should colorize (or if you are viewing a test instance, you'll see a result added to the list.)

**Comment by seancribbs** [comment]
WFM now, no errors in the logs and I get the desktop notifications like a champ. I might be missing some image because I got a "broken image" icon next to the notification.

**Comment by cmeiklejohn** [comment]
:)

**Comment by cmeiklejohn** [comment]
OK to merge?

**Comment by seancribbs** [comment]
not bad for a human

Ready to merge.

**Comment by cmeiklejohn** [comment]
lolololololo glad you caught up on meme innovation while you were gone

**Comment by cmeiklejohn** [comment]
Merged && deployed.

**Pull request merged**
