### PR TITLE
Add repl_aae_fullsync test.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
@buddhisthead @seancribbs

### CODE REVIEW

**Comment by seancribbs** [comment]
:+1:

**Comment by buddhisthead** [comment]
Shouldn't this test pass before we add it?

**Comment by cmeiklejohn** [comment]
Considering it should have been added back at 1.4, my vote is get it in now as a constant reminder that we need to get it passing before someone forgets.

**Comment by seancribbs** [comment]
Yeah, if it has been merged to riak_test and applies to any release, it should be in the matrix.

**Comment by cmeiklejohn** [comment]
Agreed, can you merge and deploy when you have a chance?

**Comment by seancribbs** [comment]
Deployed

**Pull request merged**
