### PR TITLE
Add models and start modeling UI.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
@seancribbs does this look like the right modeling for the UI? /cc @joedevivo

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
- Each project has a series of tests run for every version/platform.  
- A project has multiple scorecards (representing a platform build as of X date)
- Each scorecard has a series of test results pointing to that test for a particular backend.

Thoughts?  I took a wild guess since I didn't see any of this in the ruby backend yet.

**Comment by seancribbs** [comment]
This looks really great. I don't see anything showing up in the UI yet, though, is there anything special I need to do?

**Comment by seancribbs** [comment]
Aha, Chrome is complaining:

```
Uncaught Error: assertion failed: The name you supplied sidebar did not resolve to a view SidebarView vendor.js:1642
```

**Comment by cmeiklejohn** [comment]
Ah, ugh.  Maybe I had something cached?  I didn't run into that issue.  I'll take a look today.

The UI should currently only show a list of projects because I wanted to be sure about the modeling before building the UI out further.

**Comment by cmeiklejohn** [comment]
Weird, a fresh checkout of this and I'm still not running into the javascript errors.

**Comment by cmeiklejohn** [comment]
Updated to use production data.

**Comment by seancribbs** [comment]
I subsumed your branch and continued with it while you were out. It's already in master.

**Pull request closed without merging**
