### PR TITLE
Add backup/restore test

### PR DESCRIPTION
**Pull request by engelsanchez**
/cc @cmeiklejohn 
I added this simple line and populated the DB. It appeared on the app while reporting and everything, though I couldn't run all tests through it because they still get stuck (waiting for Joe's new changes). Anyway, is there anything else I need to worry about when adding a test?

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@joedevivo Any min/max requirements here?  Also, is the seed still idempotent?

**Comment by engelsanchez** [comment]
Do you mean riak version requirements? I don't know of any. This is a port of an old test.

**Comment by joedevivo** [comment]
this test should work for any version of riak testable by riak_test

**Comment by cmeiklejohn** [comment]
:+1:

**Pull request merged**
